In [159]:
import numpy as np #для матричных вычислений
import pandas as pd #для анализа и предобработки данных
import matplotlib.pyplot as plt #для визуализации
import seaborn as sns #для визуализации

from sklearn import linear_model #линейные модели
from sklearn import metrics #метрики
from sklearn import preprocessing #предобработка
from sklearn.model_selection import train_test_split #разделение выборки
import category_encoders as ce

In [160]:
data = pd.read_csv('C:\VS Code/archive (3)/Life Expectancy Data.csv')
data.head(10)

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
5,Afghanistan,2010,Developing,58.8,279.0,74,0.01,79.679367,66.0,1989,...,66.0,9.20,66.0,0.1,553.328940,2883167.0,18.4,18.4,0.448,9.2
6,Afghanistan,2009,Developing,58.6,281.0,77,0.01,56.762217,63.0,2861,...,63.0,9.42,63.0,0.1,445.893298,284331.0,18.6,18.7,0.434,8.9
7,Afghanistan,2008,Developing,58.1,287.0,80,0.03,25.873925,64.0,1599,...,64.0,8.33,64.0,0.1,373.361116,2729431.0,18.8,18.9,0.433,8.7
8,Afghanistan,2007,Developing,57.5,295.0,82,0.02,10.910156,63.0,1141,...,63.0,6.73,63.0,0.1,369.835796,26616792.0,19.0,19.1,0.415,8.4
9,Afghanistan,2006,Developing,57.3,295.0,84,0.03,17.171518,64.0,1990,...,58.0,7.43,58.0,0.1,272.563770,2589345.0,19.2,19.3,0.405,8.1

In [161]:
data[data['Country'] == 'South Sudan']

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
2409,South Sudan,2015,Developing,57.3,332.0,26,NaN,0.000000,31.0,878,...,41.0,NaN,31.0,3.4,758.725782,11882136.0,NaN,NaN,0.421,4.9
2410,South Sudan,2014,Developing,56.6,343.0,26,NaN,46.074469,NaN,441,...,44.0,2.74,39.0,3.5,1151.861715,1153971.0,NaN,NaN,0.421,4.9
2411,South Sudan,2013,Developing,56.4,345.0,26,NaN,47.444530,NaN,525,...,5.0,2.62,45.0,3.6,1186.113250,1117749.0,NaN,NaN,0.417,4.9
2412,South Sudan,2012,Developing,56.0,347.0,26,NaN,38.338232,NaN,1952,...,64.0,2.77,59.0,3.8,958.455810,1818258.0,NaN,NaN,0.419,4.9
2413,South Sudan,2011,Developing,55.4,355.0,27,NaN,0.000000,NaN,1256,...,66.0,NaN,61.0,3.9,176.971300,1448857.0,NaN,NaN,0.429,4.9
2414,South Sudan,2010,Developing,55.0,359.0,27,NaN,0.000000,NaN,0,...,NaN,NaN,NaN,4.0,1562.239346,167192.0,NaN,NaN,0.000,0.0
2415,South Sudan,2009,Developing,54.3,369.0,27,NaN,0.000000,NaN,0,...,NaN,NaN,NaN,4.2,1264.789980,967667.0,NaN,NaN,0.000,0.0
2416,South Sudan,2008,Developing,53.6,377.0,27,NaN,0.000000,NaN,0,...,NaN,NaN,NaN,4.2,1678.711862,9263136.0,NaN,NaN,0.000,0.0
2417,South Sudan,2007,Developing,53.1,381.0,27,NaN,0.000000,NaN,0,...,NaN,NaN,NaN,4.2,NaN,88568.0,NaN,NaN,0.000,0.0
2418,South Sudan,2006,Developing,52.5,383.0,28,NaN,0.000000,NaN,0,...,NaN,NaN,NaN,4.1,NaN,8468152.0,NaN,NaN,0.000,0.0
2419,South Sudan,2005,Developing,51.9,383.0,28,NaN,0.000000,NaN,0,...,NaN,NaN,NaN,3.9,NaN,818877.0,NaN,NaN,0.000,0.0
2420,South Sudan,2004,Developing,51.4,383.0,29,NaN,0.000000,NaN,0,...,NaN,NaN,NaN,3.8,NaN,7787655.0,NaN,NaN,0.000,0.0
2421,South Sudan,2003,Developing,58.0,383.0,29,NaN,0.000000,NaN,0,...,NaN,NaN,NaN,3.5,NaN,751642.0,NaN,NaN,0.000,0.0
2422,South Sudan,2002,Developing,52.0,382.0,30,NaN,0.000000,NaN,0,...,NaN,NaN,NaN,3.3,NaN,7237276.0,NaN,NaN,0.000,0.0
2423,South Sudan,2001,Developing,49.6,381.0,30,NaN,0.000000,NaN,0,...,NaN,NaN,NaN,3.0,NaN,6974442.0,NaN,NaN,0.000,0.0
2424,South Sudan,2000,Developing,48.9,38.0,31,NaN,0.000000,NaN,0,...,NaN,NaN,NaN,2.7,NaN,67656.0,NaN,NaN,0.000,0.0

1. Country - страна
2. Year - год
3. Status - статус
4. Life expectancy - Ожидаемая продолжительность жизни (целевой признак)
5. Adult Mortality - смертность среди взрослых
6. infant deaths - младенческая смертность
7. Alcohol - алкоголь
8. percentage expenditure - процент  расходов
9.  Hepatitis B - Гепатит  В
10. Measles - Корь
11. BMI - индекс массы   тела
12. under-five deaths - смертей в возрасте до пяти лет
13. Polio - Полиомиелит
14. Total expenditure - Общие расходы
15.  Diphtheria  - дифтирия
16.  HIV/AIDS - ВИЧ/СПИД
17.  GDP - ВВП
18.  Population - население
19. thinness  1-19 years - худоба 1-19 лет
20. thinness 5-9 years - худоба 5-9 лет 
21. Income composition of resources - Структура доходов ресурсов
22. Schooling - школьное образование

In [162]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          2938 non-null   object
 1   Year                             2938 non-null   int64
 2   Status                           2938 non-null   object
 3   Life expectancy                  2928 non-null   float64
 4   Adult Mortality                  2928 non-null   float64
 5   infant deaths                    2938 non-null   int64
 6   Alcohol                          2744 non-null   float64
 7   percentage expenditure           2938 non-null   float64
 8   Hepatitis B                      2385 non-null   float64
 9   Measles                          2938 non-null   int64
 10   BMI                             2904 non-null   float64
 11  under-five deaths                2938 non-null   int64
 12  Polio                            2919 non-null   float64
 13  Total expenditure                2712 non-null   float64
 14  Diphtheria                       2919 non-null   float64
 15   HIV/AIDS                        2938 non-null   float64
 16  GDP                              2490 non-null   float64
 17  Population                       2286 non-null   float64
 18   thinness  1-19 years            2904 non-null   float64
 19   thinness 5-9 years              2904 non-null   float64
 20  Income composition of resources  2771 non-null   float64
 21  Schooling                        2775 non-null   float64
dtypes: float64(16), int64(4), object(2)
memory usage: 505.1+ KB

In [163]:
display(data.isnull().sum())

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
dtype: int64

In [164]:
country_notdata_alco = list(data[data['Alcohol'].isnull()]['Country'])
set(country_notdata_alco)

{'Algeria',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bhutan',
 'Bolivia (Plurinational State of)',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czechia',
 "Côte d'Ivoire",
 "Democratic People's Republic of Korea",
 'Democratic Republic of the Congo',
 'Denmark',
 'Djibouti',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Fiji',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Grenada',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran (Islamic Republic of)',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kuwait',
 'Kyrgyzstan',
 "Lao People's Democratic Republic",
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Lithuania',
 'Luxembourg',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia (Federated States of)',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Oman',
 'Pakistan',
 'Palau',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Qatar',
 'Republic of Korea',
 'Republic of Moldova',
 'Romania',
 'Russian Federation',
 'Rwanda',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syrian Arab Republic',
 'Tajikistan',
 'Thailand',
 'The former Yugoslav republic of Macedonia',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Republic of Tanzania',
 'United States of America',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela (Bolivarian Republic of)',
 'Viet Nam',
 'Yemen',
 'Zambia',
 'Zimbabwe'}

In [165]:
data[data['Country'] == 'Algeria']

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
32,Algeria,2015,Developing,75.6,19.0,21,NaN,0.000000,95.0,63,...,95.0,NaN,95.0,0.1,4132.762920,39871528.0,6.0,5.8,0.743,14.4
33,Algeria,2014,Developing,75.4,11.0,21,0.01,54.237318,95.0,0,...,95.0,7.21,95.0,0.1,547.851700,39113313.0,6.0,5.8,0.741,14.4
34,Algeria,2013,Developing,75.3,112.0,21,0.53,544.450743,95.0,25,...,95.0,7.12,95.0,0.1,5471.866766,38338562.0,5.9,5.8,0.737,14.4
35,Algeria,2012,Developing,75.1,113.0,21,0.66,555.926083,95.0,18,...,95.0,6.14,95.0,0.1,5564.825660,37565847.0,5.9,5.8,0.732,14.4
36,Algeria,2011,Developing,74.9,116.0,21,0.56,509.002041,95.0,112,...,95.0,5.29,95.0,0.1,5432.252300,36819558.0,5.9,5.8,0.724,14.0
37,Algeria,2010,Developing,74.7,119.0,21,0.45,430.717586,95.0,103,...,95.0,5.12,95.0,0.1,4463.394675,36117637.0,5.9,5.8,0.714,13.6
38,Algeria,2009,Developing,74.4,123.0,20,0.50,352.063642,94.0,107,...,94.0,5.36,95.0,0.1,3868.831230,3546576.0,6.0,5.9,0.705,13.1
39,Algeria,2008,Developing,74.1,126.0,20,0.46,43.087173,91.0,217,...,92.0,4.20,93.0,0.1,495.254866,3486715.0,6.0,5.9,0.697,12.6
40,Algeria,2007,Developing,73.8,129.0,20,0.44,320.323924,9.0,0,...,95.0,3.82,95.0,0.1,3935.183343,34376.0,6.0,5.9,0.690,12.3
41,Algeria,2006,Developing,73.4,132.0,20,0.36,270.240196,8.0,944,...,95.0,3.36,95.0,0.1,3464.617900,33777915.0,6.1,6.0,0.686,12.3
42,Algeria,2005,Developing,72.9,136.0,19,0.50,2.548923,83.0,2302,...,88.0,3.24,88.0,0.1,31.122378,33288437.0,6.1,6.0,0.680,12.0
43,Algeria,2004,Developing,72.3,14.0,19,0.45,220.393699,81.0,3289,...,86.0,3.54,86.0,0.1,2598.982300,3283196.0,6.2,6.1,0.673,11.7
44,Algeria,2003,Developing,71.7,146.0,20,0.34,25.018523,NaN,15374,...,87.0,3.60,87.0,0.1,294.335560,3243514.0,6.3,6.1,0.663,11.5
45,Algeria,2002,Developing,71.6,145.0,20,0.36,148.511984,NaN,5862,...,86.0,3.73,86.0,0.1,1774.336730,3199546.0,6.3,6.2,0.653,11.1
46,Algeria,2001,Developing,71.4,145.0,20,0.23,147.986071,NaN,2686,...,89.0,3.84,89.0,0.1,1732.857979,31592153.0,6.4,6.3,0.644,10.9
47,Algeria,2000,Developing,71.3,145.0,21,0.25,154.455944,NaN,0,...,86.0,3.49,86.0,0.1,1757.177970,3118366.0,6.5,6.4,0.636,10.7

In [166]:
data.nunique()

Country                             193
Year                                 16
Status                                2
Life expectancy                     362
Adult Mortality                     425
infant deaths                       209
Alcohol                            1076
percentage expenditure             2328
Hepatitis B                          87
Measles                             958
 BMI                                608
under-five deaths                   252
Polio                                73
Total expenditure                   818
Diphtheria                           81
 HIV/AIDS                           200
GDP                                2490
Population                         2278
 thinness  1-19 years               200
 thinness 5-9 years                 207
Income composition of resources     625
Schooling                           173
dtype: int64

In [167]:
display(data.isnull().sum())

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
dtype: int64

In [168]:
data = data.dropna(subset=['Life expectancy '], axis=0)

In [169]:
display(data.isnull().sum())

Country                              0
Year                                 0
Status                               0
Life expectancy                      0
Adult Mortality                      0
infant deaths                        0
Alcohol                            193
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                32
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                443
Population                         644
 thinness  1-19 years               32
 thinness 5-9 years                 32
Income composition of resources    160
Schooling                          160
dtype: int64

In [170]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2928 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          2928 non-null   object
 1   Year                             2928 non-null   int64
 2   Status                           2928 non-null   object
 3   Life expectancy                  2928 non-null   float64
 4   Adult Mortality                  2928 non-null   float64
 5   infant deaths                    2928 non-null   int64
 6   Alcohol                          2735 non-null   float64
 7   percentage expenditure           2928 non-null   float64
 8   Hepatitis B                      2375 non-null   float64
 9   Measles                          2928 non-null   int64
 10   BMI                             2896 non-null   float64
 11  under-five deaths                2928 non-null   int64
 12  Polio                            2909 non-null   float64
 13  Total expenditure                2702 non-null   float64
 14  Diphtheria                       2909 non-null   float64
 15   HIV/AIDS                        2928 non-null   float64
 16  GDP                              2485 non-null   float64
 17  Population                       2284 non-null   float64
 18   thinness  1-19 years            2896 non-null   float64
 19   thinness 5-9 years              2896 non-null   float64
 20  Income composition of resources  2768 non-null   float64
 21  Schooling                        2768 non-null   float64
dtypes: float64(16), int64(4), object(2)
memory usage: 526.1+ KB

In [171]:
skip = data.isnull().sum()[data.isnull().sum() > 0].index
skip

Index(['Alcohol', 'Hepatitis B', ' BMI ', 'Polio', 'Total expenditure',
       'Diphtheria ', 'GDP', 'Population', ' thinness  1-19 years',
       ' thinness 5-9 years', 'Income composition of resources', 'Schooling'],
      dtype='object')

In [172]:
countries = data['Country'].unique()
countries

array(['Afghanistan', 'Albania', 'Algeria', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia (Plurinational State of)', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', "Côte d'Ivoire", 'Cabo Verde',
       'Cambodia', 'Cameroon', 'Canada', 'Central African Republic',
       'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo',
       'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czechia',
       "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Fiji',
       'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany',
       'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hungary',
       'Iceland', 'India', 'Indonesia', 'Iran (Islamic Republic of)',
       'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan',
       "Lao People's Democratic Republic", 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libya', 'Lithuania', 'Luxembourg', 'Madagascar',
       'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Mauritania',
       'Mauritius', 'Mexico', 'Micronesia (Federated States of)',
       'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua',
       'Niger', 'Nigeria', 'Norway', 'Oman', 'Pakistan', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Qatar', 'Republic of Korea', 'Republic of Moldova',
       'Romania', 'Russian Federation', 'Rwanda', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Swaziland', 'Sweden',
       'Switzerland', 'Syrian Arab Republic', 'Tajikistan', 'Thailand',
       'The former Yugoslav republic of Macedonia', 'Timor-Leste', 'Togo',
       'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
       'Turkmenistan', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom of Great Britain and Northern Ireland',
       'United Republic of Tanzania', 'United States of America',
       'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela (Bolivarian Republic of)', 'Viet Nam', 'Yemen',
       'Zambia', 'Zimbabwe'], dtype=object)

In [173]:
display(data.isnull().sum())

Country                              0
Year                                 0
Status                               0
Life expectancy                      0
Adult Mortality                      0
infant deaths                        0
Alcohol                            193
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                32
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                443
Population                         644
 thinness  1-19 years               32
 thinness 5-9 years                 32
Income composition of resources    160
Schooling                          160
dtype: int64

In [174]:
for col in skip:
    for country in countries:
        mask = data['Country'] == country
        if data[mask][col].isnull().sum() == 16:
            value = {col: 0}
            data[mask] = data[mask].fillna(value)
        else:     
            value = {col: data[mask][col].mean()}
            data[mask] = data[mask].fillna(value)

In [175]:
display(data.isnull().sum())

Country                            0
Year                               0
Status                             0
Life expectancy                    0
Adult Mortality                    0
infant deaths                      0
Alcohol                            0
percentage expenditure             0
Hepatitis B                        0
Measles                            0
 BMI                               0
under-five deaths                  0
Polio                              0
Total expenditure                  0
Diphtheria                         0
 HIV/AIDS                          0
GDP                                0
Population                         0
 thinness  1-19 years              0
 thinness 5-9 years                0
Income composition of resources    0
Schooling                          0
dtype: int64

In [176]:
data[data['Country'] == 'South Sudan']

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
2409,South Sudan,2015,Developing,57.3,332.0,26,0.0,0.000000,31.0,878,...,41.0,2.71,31.0,3.4,758.725782,11882136.0,0.0,0.0,0.421,4.9
2410,South Sudan,2014,Developing,56.6,343.0,26,0.0,46.074469,31.0,441,...,44.0,2.74,39.0,3.5,1151.861715,1153971.0,0.0,0.0,0.421,4.9
2411,South Sudan,2013,Developing,56.4,345.0,26,0.0,47.444530,31.0,525,...,5.0,2.62,45.0,3.6,1186.113250,1117749.0,0.0,0.0,0.417,4.9
2412,South Sudan,2012,Developing,56.0,347.0,26,0.0,38.338232,31.0,1952,...,64.0,2.77,59.0,3.8,958.455810,1818258.0,0.0,0.0,0.419,4.9
2413,South Sudan,2011,Developing,55.4,355.0,27,0.0,0.000000,31.0,1256,...,66.0,2.71,61.0,3.9,176.971300,1448857.0,0.0,0.0,0.429,4.9
2414,South Sudan,2010,Developing,55.0,359.0,27,0.0,0.000000,31.0,0,...,44.0,2.71,47.0,4.0,1562.239346,167192.0,0.0,0.0,0.000,0.0
2415,South Sudan,2009,Developing,54.3,369.0,27,0.0,0.000000,31.0,0,...,44.0,2.71,47.0,4.2,1264.789980,967667.0,0.0,0.0,0.000,0.0
2416,South Sudan,2008,Developing,53.6,377.0,27,0.0,0.000000,31.0,0,...,44.0,2.71,47.0,4.2,1678.711862,9263136.0,0.0,0.0,0.000,0.0
2417,South Sudan,2007,Developing,53.1,381.0,27,0.0,0.000000,31.0,0,...,44.0,2.71,47.0,4.2,1092.233631,88568.0,0.0,0.0,0.000,0.0
2418,South Sudan,2006,Developing,52.5,383.0,28,0.0,0.000000,31.0,0,...,44.0,2.71,47.0,4.1,1092.233631,8468152.0,0.0,0.0,0.000,0.0
2419,South Sudan,2005,Developing,51.9,383.0,28,0.0,0.000000,31.0,0,...,44.0,2.71,47.0,3.9,1092.233631,818877.0,0.0,0.0,0.000,0.0
2420,South Sudan,2004,Developing,51.4,383.0,29,0.0,0.000000,31.0,0,...,44.0,2.71,47.0,3.8,1092.233631,7787655.0,0.0,0.0,0.000,0.0
2421,South Sudan,2003,Developing,58.0,383.0,29,0.0,0.000000,31.0,0,...,44.0,2.71,47.0,3.5,1092.233631,751642.0,0.0,0.0,0.000,0.0
2422,South Sudan,2002,Developing,52.0,382.0,30,0.0,0.000000,31.0,0,...,44.0,2.71,47.0,3.3,1092.233631,7237276.0,0.0,0.0,0.000,0.0
2423,South Sudan,2001,Developing,49.6,381.0,30,0.0,0.000000,31.0,0,...,44.0,2.71,47.0,3.0,1092.233631,6974442.0,0.0,0.0,0.000,0.0
2424,South Sudan,2000,Developing,48.9,38.0,31,0.0,0.000000,31.0,0,...,44.0,2.71,47.0,2.7,1092.233631,67656.0,0.0,0.0,0.000,0.0

In [177]:
data['Status'].unique()

array(['Developing', 'Developed'], dtype=object)

In [178]:
data['Status'] = data['Status'].apply(lambda x: 1 if x == 'Developed' else 0 )

In [179]:
object_columns = [s for s in data.columns if data[s].dtypes == 'object']
not_object_data = data.copy()
not_object_data.drop(object_columns, axis = 1, inplace=True)

In [180]:
def print_metrics(y_train, y_train_predict, y_test, y_test_predict):
    print('Train R^2: {:.3f}'.format(metrics.r2_score(y_train, y_train_predict)))
    print('Train MAE: {:.3f}'.format(metrics.mean_absolute_error(y_train, y_train_predict)))
    print('Train MAPE: {:.3f}'.format(metrics.mean_absolute_percentage_error(y_train, y_train_predict)*100))
    print('\n')
    print('Test R^2: {:.3f}'.format(metrics.r2_score(y_test, y_test_predict)))
    print('Test MAE: {:.3f}'.format(metrics.mean_absolute_error(y_test, y_test_predict)))
    print('Train MAPE: {:.3f}'.format(metrics.mean_absolute_percentage_error(y_test, y_test_predict)*100))

In [181]:
X = not_object_data.drop('Life expectancy ', axis=1)
y = not_object_data['Life expectancy ']

In [182]:
#Создаем тренировочную и тестовую выборки с помощью train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, #таблица с наблюдениями и столбец с правильным ответами
    test_size=0.2, #размер тестовой выборки
    random_state=42 #число отвечающее за генерацию случайных чисел
)
#Выводим размеры полученных выборок
print('Train shape: {}'.format(X_train.shape))
print('Test shape: {}'.format(X_test.shape))

Train shape: (2342, 20)
Test shape: (586, 20)

In [183]:
#Инициализируем объект класса линейная регрессия
lr = linear_model.LinearRegression()
#Обучаем модель - ищем параметры
lr.fit(X_train, y_train)
#Делаем предсказание для каждой из выборок
y_train_pred = lr.predict(X_train)
y_test_pred = lr.predict(X_test)
#Выводим результирующие метрики
print_metrics(y_train, y_train_pred, y_test, y_test_pred)

Train R^2: 0.799
Train MAE: 3.235
Train MAPE: 4.939


Test R^2: 0.797
Test MAE: 3.108
Train MAPE: 4.755

In [184]:
#Создаем объект для min-max нормализации
scaler = preprocessing.MinMaxScaler()
#Вычисляем параметры для нормализации - min и max для каждого столбца
scaler.fit(X_train)
#Производим преобразование для каждой из выборок
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

#Инициализируем объект класса линейная регрессия
sgd_lr = linear_model.SGDRegressor(random_state=42)
#Обучаем модель - ищем параметры
sgd_lr.fit(X_train_scaled, y_train)
#Делаем предсказание для каждой из выборок
y_train_pred = sgd_lr.predict(X_train_scaled)
y_test_pred = sgd_lr.predict(X_test_scaled)
#Выводим результирующие метрики
print_metrics(y_train, y_train_pred, y_test, y_test_pred)

Train R^2: 0.783
Train MAE: 3.353
Train MAPE: 5.116


Test R^2: 0.789
Test MAE: 3.149
Train MAPE: 4.802

Перекодируем признак страны

In [185]:
country_data = data.copy()

In [186]:
bin_encoder = ce.BinaryEncoder(cols=['Country']) # указываем столбец для кодирования
type_bin = bin_encoder.fit_transform(country_data['Country'])
country_data = pd.concat([country_data, type_bin], axis=1)
country_data

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Income composition of resources,Schooling,Country_0,Country_1,Country_2,Country_3,Country_4,Country_5,Country_6,Country_7
0,Afghanistan,2015,0,65.0,263.0,62,0.01,71.279624,65.0,1154,...,0.479,10.1,0,0,0,0,0,0,0,1
1,Afghanistan,2014,0,59.9,271.0,64,0.01,73.523582,62.0,492,...,0.476,10.0,0,0,0,0,0,0,0,1
2,Afghanistan,2013,0,59.9,268.0,66,0.01,73.219243,64.0,430,...,0.470,9.9,0,0,0,0,0,0,0,1
3,Afghanistan,2012,0,59.5,272.0,69,0.01,78.184215,67.0,2787,...,0.463,9.8,0,0,0,0,0,0,0,1
4,Afghanistan,2011,0,59.2,275.0,71,0.01,7.097109,68.0,3013,...,0.454,9.5,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,0,44.3,723.0,27,4.36,0.000000,68.0,31,...,0.407,9.2,1,0,1,1,0,1,1,1
2934,Zimbabwe,2003,0,44.5,715.0,26,4.06,0.000000,7.0,998,...,0.418,9.5,1,0,1,1,0,1,1,1
2935,Zimbabwe,2002,0,44.8,73.0,25,4.43,0.000000,73.0,304,...,0.427,10.0,1,0,1,1,0,1,1,1
2936,Zimbabwe,2001,0,45.3,686.0,25,1.72,0.000000,76.0,529,...,0.427,9.8,1,0,1,1,0,1,1,1
2937,Zimbabwe,2000,0,46.0,665.0,24,1.68,0.000000,79.0,1483,...,0.434,9.8,1,0,1,1,0,1,1,1

In [187]:
country_data.drop('Country', axis = 1, inplace=True)

In [188]:
X = country_data.drop('Life expectancy ', axis=1)
y = country_data['Life expectancy ']

In [189]:
#Создаем тренировочную и тестовую выборки с помощью train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, #таблица с наблюдениями и столбец с правильным ответами
    test_size=0.2, #размер тестовой выборки
    random_state=42 #число отвечающее за генерацию случайных чисел
)
#Выводим размеры полученных выборок
print('Train shape: {}'.format(X_train.shape))
print('Test shape: {}'.format(X_test.shape))

Train shape: (2342, 28)
Test shape: (586, 28)

In [190]:
#Инициализируем объект класса линейная регрессия
lr = linear_model.LinearRegression()
#Обучаем модель - ищем параметры
lr.fit(X_train, y_train)
#Делаем предсказание для каждой из выборок
y_train_pred = lr.predict(X_train)
y_test_pred = lr.predict(X_test)
#Выводим результирующие метрики
print_metrics(y_train, y_train_pred, y_test, y_test_pred)

Train R^2: 0.803
Train MAE: 3.211
Train MAPE: 4.896


Test R^2: 0.802
Test MAE: 3.092
Train MAPE: 4.717

In [191]:
#Создаем объект для min-max нормализации
scaler = preprocessing.MinMaxScaler()
#Вычисляем параметры для нормализации - min и max для каждого столбца
scaler.fit(X_train)
#Производим преобразование для каждой из выборок
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

#Инициализируем объект класса линейная регрессия
sgd_lr = linear_model.SGDRegressor(random_state=42)
#Обучаем модель - ищем параметры
sgd_lr.fit(X_train_scaled, y_train)
#Делаем предсказание для каждой из выборок
y_train_pred = sgd_lr.predict(X_train_scaled)
y_test_pred = sgd_lr.predict(X_test_scaled)
#Выводим результирующие метрики
print_metrics(y_train, y_train_pred, y_test, y_test_pred)

Train R^2: 0.787
Train MAE: 3.339
Train MAPE: 5.085


Test R^2: 0.793
Test MAE: 3.161
Train MAPE: 4.802

In [192]:
import math

In [193]:
x1 = 0.3
x2 = 3

In [194]:
z = 1 + 5 * x1 - 0.3 * x2
z

1.6

In [195]:
p = 1 / (1 + math.exp(-z))
p

0.8320183851339245